language: php

php:
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: forum-com-tdd