language: php

php:
  - "7.1"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: forum-com-tdd
    on:
    branch: master
  api_key:
    secure: qBsz+CHWl4r4cJkHQ2bO5DoiwYKPn4LKnyFO420b5Lt5ESC1ZsmI1+UUi+Fz5EzY0zJ4WwvuM4/fNG1jCkQj49RI708sMiHGKIegvswGr3VFf61Bg+oss1Bxc5FRC6jrqqH9Jq2buzrmfdSnDljSGWiaT9IBZWuQo4LkvIB7Do0fD94Vm/rQcEoxCeUXuXGsJ47YAAFlfirF3VvrBN+lS4/dgvr9PezPu9i50wr+bSt1/ciLP06N3Co6yBNeIqYMcuCpCzsb9nv74SxZnap4ggik6+5Vyx0X738gQDU7K8fOc4xfmoy8/uK7uucmTGdHWP6gd8WEZaM0WQbDj/rwwUG3oaeOBOHNrEbcU2ZpYjhDZBsiOX0iQJS490YhChMmEIjUCYjgJvPC0oQ0W8ILc0xKOX73ViIQk9ZY4eKzin23fFFgUllfd8G+/Pala5tOT6QIqjeDmzwBeEgMvLgnFqQ6KSxqAVGlppK6Tk8t3SVCL9wi4QQuUlhfOzXtOnz4n9cQYrFKSaBZotdc+4NsJmr/w4/ZNjVLftU04P+kvO+ZyioVsBpoBTVOpb4VUSCRAkN9KsWrwMMWHVOukDows4eeeB0E4rqRjsQigaNKWb2V5kRB3/FWS/p6sSxUHEBEcEgyrL6x5RZuxx7GZYCjtQVOoL4tDxYFDAS9xtlXzyM=
    secure: YfOWH0w/wcXo930jhR0ds7NR2JNJxBckxWaNLaMQ4Qshf26IPM7H1TfxJKmQ1Pg1x8Qkbcmea0ER7HG1zDliFQhVCFk8JPbGqwqCaDZ7S2nFJCv10G1C8BLgI9uAMXNOCgs2XV14byz4QBfUbkMxCy6JzPd0jZRMhMQb5iWDECiIgqG5MsJ9LbcRrZc/aPvcm13wmADyN6oz9uTMXN3kT9GWqop7Y6/eTMB8bhE0LpMVldUrTAjpLDiPhnbnC7LacYQpxW8gLIWioH6iGd82k4UmFlpcon0bP18OU32keuNzV2nUnTXCMZxkRk3thCykjTnQJZEP0frTO5Aa95ZU9cqam2ozki/bcrWUb1WzMtVDrVSBQ02BjUj9hn6YUbijUHX8qlJN0nrH9gHzzCKZ5XFJm/s5/aRoUN82Qp1o87GLnZ1m2mVg48F1BxqsK22xWmmfB8TGZ3DOEnEanli3DlHBz/xh62yNbYEE3O/VNZg/KC0DnLcpKN7Sm6Gw5g7zMRYK6Zqc9ED5znXcVNzGzrQDa/FFrUf82nhdbLt4l027i1PEYvbmiAVty3SXWrowf7/dJ5X9i5OQ91Jq+mnIhb1Lfdfr5jM9JitVwVL62dahBVNQRj3aO3LSwCeb1uLQ51pr3aT1e+UD80E9n4gkB5sfAnySphqYEVT+UHFkmfY=
notifications:
  email:
