language: php
php:
  - 7.1

before_script:

  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
- php artisan key:generate
- vendor/bin/phpunit

notifications:
  email: 
    recipients:
      - kap-araujo@outlook.com
    on_success: change
    on_failure: always